GH1051 Drop astype tests for Mac arm for float128 and complex256
pandas-dev/pandas-stubs pull request #1057
Opened 2024-11-26 03:03 UTC by loicdiridollou

- [x] Closes #1051
- [x] Tests added: Please use `assert_type()` to assert the type of any return value

2024-11-26 22:47 UTC, loicdiridollou commented
Needed to let poetry choose the right version of `tables`, wondering if it is okay, at least we will need that to move to supporting python3.13.

2024-11-27 15:08 UTC, Dr-Irv requested changes
I think we should update the version of `tables`

2024-11-27 15:08 UTC, Dr-Irv commented on pyproject.toml
> +tables = { version = ">=3.9.2", python = "<4" }   # 3.8.0 depends on blosc2 which caps python to <4
version 3.10.1 is out, and it was what was used in the tests, so changing this from 3.9.2 to 3.10.1 is warranted.

2024-11-27 18:55 UTC, Dr-Irv approved these changes
thanks @loicdiridollou

2024-11-27 18:55 UTC, merged