Allow `num` to be a `complex` type to support `Series` operations.
pandas-dev/pandas-stubs pull request #106
Opened 2022-07-06 17:14 UTC by aholmes

Closes #103

- [ ] Closes #103(Replace xxxx with the Github issue number)
- [ ] Tests added: None. It doesn't look like types are directly asserted in existing tests?

2022-07-06 20:47 UTC, Dr-Irv requested changes
Can you add a test with a reference to the original issue?

2022-07-06 20:52 UTC, aholmes commented
> Can you add a test with a reference to the original issue?

Sure - do you have an example of the kind of test you would like to see for this change? I was looking for something similar, but didn't see anything.

2022-07-07 02:32 UTC, merged

2022-07-07 02:32 UTC, Dr-Irv commented
Thanks @aholmes

2022-07-07 02:32 UTC, Dr-Irv approved these changes