BUG: Correct Categorical.codes
pandas-dev/pandas-stubs pull request #112
Opened 2022-07-07 07:56 UTC by bashtage

Set type to correct type

- [X] Closes #111 (Replace xxxx with the Github issue number)
- [X] Tests added: Please use `assert_type()` to assert the type of any return value

2022-07-07 12:18 UTC, Dr-Irv requested changes

2022-07-07 12:18 UTC, Dr-Irv commented on tests/test_series.py
> +    codes = cat.codes
Can you do this instead?
1.  import `np_ndarray_int` as follows at the top:
```python
if TYPE_CHECKING:
    from pandas._typing import np_ndarray_int
```
2. Then  you can remove the type of `codes` in the test, and just do:
```python
assert_type(cat.codes, "np_ndarray_int")
```

2022-07-07 12:33 UTC, Dr-Irv requested changes

2022-07-07 12:33 UTC, Dr-Irv commented on tests/test_series.py
> +    codes = cat.codes
Needs the `assert_type`

2022-07-10 02:24 UTC, Dr-Irv commented
@bashtage can you add the `assert_type()` as discussed above?  Then we can get this one done.

2022-07-10 23:32 UTC, bashtage commented on tests/test_series.py
> +    codes = cat.codes
Added

2022-07-11 06:42 UTC, bashtage commented
I had to noqa the import to get it to pass flake8 since the import is only used in the assert type.

2022-07-11 12:11 UTC, Dr-Irv approved these changes
Thanks @bashtage

2022-07-11 12:12 UTC, merged

2022-07-11 12:16 UTC, twoertwein commented
> I had to noqa the import to get it to pass flake8 since the import is only used in the assert type.

The second argument of `assert_type` can not only be of type `str` but also the type itself.

2022-07-11 17:52 UTC, bashtage commented
@twoertwein When I remove the quotes it doesn't work in two different ways:

1. If I leave the if TYPE_CHCKING on the import, pytest fails `NameError: name 'np_ndarray_int' is not defined`
2. If I take away the if TYPECHECKING on the import, I get ` ImportError: cannot import name 'np_ndarray_int' from 'pandas._typing'`