Allow strings to crosstab's normalize argument
pandas-dev/pandas-stubs pull request #200
Opened 2022-08-17 13:52 UTC by TomFryers

- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value
These are allowed ([docs page](https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html?highlight=crosstab#pandas.crosstab)).

2022-08-17 14:01 UTC, ruler501 commented on pandas-stubs/core/reshape/pivot.pyi
> +    normalize: bool | Literal["all", "index", "columns"] = ...,
Literal 0, 1 are also allowed

2022-08-17 14:16 UTC, Dr-Irv requested changes
Can you also add a test for this?

Adding a test to `test_pandas.py` would be appropriate.

2022-08-17 20:04 UTC, Dr-Irv requested changes
CI failed.  Need to run `poe style` on the code

2022-08-18 12:12 UTC, Dr-Irv approved these changes
Thanks @TomFryers

2022-08-18 12:12 UTC, merged