ENH: Synchronize ORC with upstream
pandas-dev/pandas-stubs pull request #204
Opened 2022-08-18 10:54 UTC by bashtage

Synchronize the orc read and write functions with upstream pandas

2022-08-18 10:55 UTC, bashtage commented
No tests because it would require pyarrow, which is not installed.

2022-08-18 12:07 UTC, Dr-Irv requested changes

2022-08-18 12:07 UTC, Dr-Irv commented on pandas-stubs/io/orc.pyi
> +    columns: list[str] | None = ...,
Should this be `list[HashableT]` ?

2022-08-18 12:07 UTC, Dr-Irv commented on pandas-stubs/io/orc.pyi
> +def to_orc(
`pandas.io.to_orc()` is not documented, but v1.5 will have `DataFrame.to_orc()`, so can you put the stub there?

2022-08-18 12:33 UTC, Dr-Irv commented
> No tests because it would require pyarrow, which is not installed.

It would just have to go in the section in `pyproject.toml` under `[tool.poetry.dev-dependencies]` so wouldn't be an installation requirement for the stubs, just for testing, and I think we should do that.

2022-08-19 12:13 UTC, Dr-Irv commented
I see that you are skipping the tests if we have pandas < 1.5.  Did you test this with `main` from pandas?

2022-08-22 16:24 UTC, bashtage commented on pandas-stubs/io/orc.pyi
> +    columns: list[str] | None = ...,
Fixed.

2022-08-22 16:36 UTC, Dr-Irv commented
I'm good with these changes, but can you answer this question: https://github.com/pandas-dev/pandas-stubs/pull/204#issuecomment-1220603356

Also need to resolve conflicts.  (realizing this is a PITA as I keep approving PR's)

2022-08-23 09:03 UTC, bashtage commented
> I see that you are skipping the tests if we have pandas < 1.5. Did you test this with `main` from pandas?

Yes, it passes on main.

2022-08-23 10:40 UTC, bashtage commented
Ready for merge.

2022-08-23 12:10 UTC, Dr-Irv approved these changes
thanks @bashtage

2022-08-23 12:10 UTC, merged