Support Python 3.11
pandas-dev/pandas-stubs pull request #398
Opened 2022-10-25 03:25 UTC by KotlinIsland

- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

2022-10-25 06:26 UTC, bashtage commented
Need to wait for lxml to have 3.11 wheels.

2022-10-25 06:31 UTC, KotlinIsland commented
https://github.com/lxml/lxml/pull/355
https://github.com/lxml/lxml/pull/356

2022-10-25 13:12 UTC, bashtage commented
There are 3.11 wheels on PyPu if 1.5.1, so it looks like 3.11 is supported by pandas.

2022-10-26 01:32 UTC, BrenoJesusFernandes commented
Be careful, looks like we still don't have  a stable version for python 3.11 for macos in github actions: https://github.com/actions/python-versions/releases/tag/3.11.0-3320066239

2022-10-26 02:09 UTC, Dr-Irv commented
CI is failing because no stable version of python 3.11 for MacOS yet and no `pyarrow` for python 3.11

2022-10-26 15:31 UTC, Dr-Irv commented
Issue is still that `pyarrow` doesn't work with python 3.11.  The CI sees no binary, then tries to build the wheel, and it fails.

There might be a workaround here to skip the requirement of pyarrow when testing on 3.11 (and then to adjust the tests accordingly to do a `pytest.skip`) but I don't know how to modify `pyproject.toml` to do that.

@BrenoJesusFernandes Any ideas on how to make the poetry requirement for `pyarrow` conditional on python <= 3.10 in `pyproject.toml` ?

2022-10-26 16:07 UTC, Dr-Irv commented
spoke with someone who is familiar with `pyarrow`, and they think 3.11 wheels will be available within a week, so maybe easiest to wait for that

2022-10-26 19:55 UTC, BrenoJesusFernandes commented
I don't get why pandas is available in python 3.11, when one requirement is not available. It's seems wrong for me. In poetry last versio, you can define multiples dependencies besides the dev-dependecies, but I think we should wait the dependecies to be available in 3.11.

2022-10-26 20:00 UTC, Dr-Irv commented
> I don't get why pandas is available in python 3.11, when one requirement is not available. It's seems wrong for me. In poetry last versio, you can define multiples dependencies besides the dev-dependecies, but I think we should wait the dependecies to be available in 3.11.

`pyarrow` is an _optional_ dependency.  So that's why `pandas` is available for python 3.11, because you can use `pandas` with python 3.11, you just can't use `pyarrow` with it.

So if there is a way to define the dependencies as one set for python <= 3.10 that we have now, and another set that is the same, except removes `pyarrow` for python 3.11, we can move forward.  Then we modify the tests that use `pyarrow` to test if `pyarrow` is available.  That's how the tests for pandas with python 3.11 are set up.

Or we wait a week (hopefully) until  `pyarrow` builds wheels for python 3.11

2022-10-26 20:17 UTC, Dr-Irv commented
> is there some test using pyarrow? if exits tests like that it is gonna fail in CI.

There are a couple of tests in `test_pandas.py` and `test_frame.py`.  They are protected with a `pytest.importorskip` .  

So we just need to modify the `pyproject.toml` file to indicate that `pyarrow` should not be installed when testing python 3.11.  Then the tests should work.

2022-10-26 20:23 UTC, BrenoJesusFernandes commented
hmm I see, so it's simple than I thought, just add something like that:

[tool.poetry.dev-dependencies]
pyarrow = { version = "currently-version", python = "<3.11" }
]

2022-10-26 20:29 UTC, Dr-Irv commented
@KotlinIsland if you want to try what @BrenoJesusFernandes suggests above, that might make the CI work.

2022-10-27 20:45 UTC, bellini666 commented
Since this is a stubs package, does it make sense to limit the upper bound of the python version? I would say that even libs shouldn't do that themselves, unless there's a very good reason.

This is very limiting for people using poetry for example due to [this issue](https://github.com/python-poetry/poetry/issues/697)

2022-10-27 20:51 UTC, Dr-Irv commented
> Since this is a stubs package, does it make sense to limit the upper bound of the python version? I would say that even libs shouldn't do that themselves, unless there's a very good reason.

The limit is there for now because we can't run a successful test with python 3.11.  We're not willing to release the stubs for a python version unless we can successfully test the stubs on that version.

In the past, we have had issues with the stubs being compatible with one version of python, but not another.  So our tests help make sure we are not making that mistake.

2022-10-30 09:49 UTC, KotlinIsland commented
Looks like `tables` and `lxml` don't have 3.11 wheels either.

2022-10-30 10:31 UTC, KotlinIsland commented
@Dr-Irv Okay, I have made `arrow`, `tables` and `lxml` conditional dependencies, and I have added a skip check for 3.11

2022-11-01 12:48 UTC, KotlinIsland commented on tests/test_io.py
> +    _arrow = pytest.importorskip("arrow")
Strange, it made the tests pass

2022-11-01 13:59 UTC, Dr-Irv commented on tests/test_io.py
> +    _arrow = pytest.importorskip("arrow")
> This is the output of pytest, it seems to me as if `test_io` is in some way using `pyarrow`?

I'm guessing there are dependencies.  So `test_orc` pattern needs `pyarrow`, `test_xml` pattern needs `lxml`, `test_hdf` pattern needs `pytables`, etc.  So we should do the skips based on the particular test (and underlying library) being done.

2022-11-02 00:15 UTC, KotlinIsland commented on tests/test_io.py
> +    _arrow = pytest.importorskip("arrow")
Hows that look?

2022-11-02 00:18 UTC, KotlinIsland commented
Looks like there is some issues with mypy: https://github.com/python/mypy/issues/13627

This is causing the ci to fail for 3.11 and will require updating mypy to 0.982

2022-11-02 03:14 UTC, Dr-Irv commented
@KotlinIsland Please see https://github.com/pandas-dev/pandas-stubs/pull/398#pullrequestreview-1161937232

We have to wait for mypy 0.990

2022-11-08 21:36 UTC, Dr-Irv commented
> @KotlinIsland Please see [#398 (review)](https://github.com/pandas-dev/pandas-stubs/pull/398#pullrequestreview-1161937232)
> 
> We have to wait for mypy 0.990

@KotlinIsland We are now testing with `mypy` 0.990 via #419 so can you merge with that, resolve conflicts, and see if the python 3.11 support will work?

2022-11-10 04:05 UTC, KotlinIsland commented
@Dr-Irv Can you trigger the CI?

2022-11-10 15:30 UTC, Dr-Irv commented
Currently two issues (but there might be more):
In `test_pandas.py`, have to use a pattern like this:
```python
import pandas.util._test_decorators as td  # at top of file somewhere

pyarrow_skip = td.skip_if_no("pyarrow")


@pyarrow_skip
def test_arrow_dtype() -> None:
    import pyarrow as pa

    check( ...
```
and in `pandas-stubs/core/arrays/arrow/dtype.pyi` (somewhere near the top):
```python
if sys.version_info < (3, 11):
    import pyarrow as pa
else:
    pa = Any
```

I'd also suggest setting up a local environment with python 3.11 and running the tests locally instead of waiting for me or someone else to do a CI approval.

2022-11-11 15:58 UTC, Dr-Irv commented
I played around a bit with this, and uncovered a pyright bug that doesn't ignore imports based on the python version test.  https://github.com/microsoft/pyright/issues/4182

So we have to wait for that to get fixed to be able to do conditional imports.

2022-11-15 21:08 UTC, Dr-Irv requested changes

2022-11-15 21:08 UTC, Dr-Irv commented on tests/test_pandas.py
> +pyarrow_skip = pytest.mark.skip
Shouldn't this be 
```python
pyarrow_skip = pytest.mark.skipif(sys.version_info >= (3, 11), "pyarrow is not available for 3.11 yet")
"""This is only needed temporarily due to no wheels being available for arrow on 3.11"""
```

2022-11-15 21:08 UTC, Dr-Irv commented on tests/test_pandas.py
> +    importskip
this import is failing.

2022-11-15 21:37 UTC, bashtage requested changes
Some fixes needed.

2022-11-15 21:37 UTC, bashtage commented on tests/test_io.py
> +lxml_skip = pytest.mark.skipif(sys.version_info >= (3, 11), "pyarrow is not available for 3.11 yet")
Wrong reason in the explanation here. Should be lxml not arrow.

2022-11-15 21:37 UTC, bashtage commented on tests/test_pandas.py
> -    pytest.importorskip("pyarrow")
These is there for a reason to protect Windows.  I think it should stay.

2022-11-15 21:37 UTC, bashtage commented on tests/test_pandas.py
> +pyarrow_skip = pytest.mark.skip
Appears to be not needed.

2022-11-20 04:47 UTC, Dr-Irv commented
I created #435 to move this along.  Took some of your ideas from here.  Had to handle an issue with pandas that's a bit thorny and want to see if I can coordinate release of this with release of pandas 1.5.2 if a PR there is included.

Thanks for working on this.  It was a great head start.

2022-11-20 04:47 UTC, closed without merging