MAINT: Fix for future change
pandas-dev/pandas-stubs pull request #409
Opened 2022-11-03 18:13 UTC by bashtage

2022-11-03 20:25 UTC, Dr-Irv requested changes
Some ideas for improvement.  Thanks for looking into this

2022-11-04 07:40 UTC, bashtage commented on tests/test_frame.py
>          df.describe(percentiles=[0.5], include="all")
I refactored it into a more sophisticated CM that can handle version ranges.

2022-11-04 07:40 UTC, bashtage commented on tests/__init__.py
> +PD_LTE_15 = parse(pd.__version__) < parse("1.5.999")
I left packaging in which is required for us.  packaging.version.parse is the universal way to do this AFAICT.

2022-11-04 13:47 UTC, Dr-Irv requested changes
Small typo in a comment, and would prefer to use pandas `Version` class

2022-11-04 13:47 UTC, Dr-Irv commented on tests/__init__.py
> +    Version conditional pytet.warns context manager
`pytest` not `pytet`

2022-11-04 13:47 UTC, Dr-Irv commented on tests/__init__.py
> +PD_LTE_15 = parse(pd.__version__) < parse("1.5.999")
Yes, but we use `pandas.util.version.Version` throughout the pandas code base (including in the pandas tests), so I'd rather follow the pandas convention.  Apparently that was adapted from `packaging` according to the source code.

2022-11-04 18:54 UTC, bashtage commented on tests/__init__.py
> +PD_LTE_15 = parse(pd.__version__) < parse("1.5.999")
Switched.

2022-11-04 18:54 UTC, bashtage commented on tests/__init__.py
> +    Version conditional pytet.warns context manager
Fixed.

2022-11-04 19:10 UTC, Dr-Irv requested changes
Looks like we need to add a stub for `pandas.util.version`

Sorry to create more work.  Hopefully `stubgen` can get you something useful.

2022-11-08 15:47 UTC, Dr-Irv commented
@bashtage Not sure how you want to handle this.  Looks like latest pandas nightly has an issue with matplotlib.

2022-11-08 17:30 UTC, bashtage commented
> @bashtage Not sure how you want to handle this. Looks like latest pandas nightly has an issue with matplotlib.

I think this one is ready and it still fixes the one issue.  The MPL seems like it will be fixed upstream.

2022-11-08 17:41 UTC, Dr-Irv commented
> > @bashtage Not sure how you want to handle this. Looks like latest pandas nightly has an issue with matplotlib.
> 
> I think this one is ready and it still fixes the one issue. The MPL seems like it will be fixed upstream.

Issue here is that the `pytest` is failing, and the typing check on nightly never happens, so maybe change the order of the tests on nightly to do the typing tests first, and then do `pytest` tests?

2022-11-08 17:49 UTC, bashtage commented
It doesn't run typing against nightly at all -- I think this makes sense since typing is internal to pandas-stubs.  It only runs pytest to try and find issues where pytest will fail.

2022-11-08 17:55 UTC, Dr-Irv commented
> It doesn't run typing against nightly at all -- I think this makes sense since typing is internal to pandas-stubs. It only runs pytest to try and find issues where pytest will fail.

OK.  I remembered the failure we had with `Version`, but that was in the regular checks.

2022-11-08 17:56 UTC, Dr-Irv approved these changes
thanks @bashtage

2022-11-08 17:56 UTC, merged