for gh-468
pandas-dev/pandas-stubs pull request #477
Opened 2022-12-19 19:29 UTC by ramvikrams

- [ ] Closes #468
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value
wanted some discussion about what could the return type for the func

2022-12-19 20:14 UTC, Dr-Irv requested changes
I don't think we want to use a decorator on top of a test function, but rather have something that lets us skip running a particular line of code based on the version so that we can keep the offending lines rather isolated.

So, for example, this test in `test_scalars.py` is failing:
```python
check(assert_type(p + offset_index, pd.PeriodIndex), pd.PeriodIndex)
```
It is failing because in the future the result will be a `pd.Index`.  So we will leave the typing alone, but need to change what is passed to `check()` based on the version number.

Other tests are changing because of date/time parsing, in which case the warnings have to be checked based on the version number.

2022-12-19 20:14 UTC, Dr-Irv commented on tests/__init__.py
> +def nigthly_test_skip(
`nightly` is misspelled

2022-12-19 20:21 UTC, ramvikrams commented on tests/__init__.py
> +def nigthly_test_skip(
i'll correct it

2022-12-19 20:21 UTC, ramvikrams commented on tests/__init__.py
> +def nigthly_test_skip(
i'll correct it

2022-12-19 20:28 UTC, ramvikrams commented
> It is failing because in the future the result will be a `pd.Index`. So we will leave the typing alone, but need to change what is passed to `check()` based on the version number.
What we wan't is to check that test on the version speicifed and check other test normally, have I understood it correctly

2022-12-19 21:52 UTC, Dr-Irv commented
> What is to be done is check a test on the version speicifed and check other test normally, have I understood it correctly

Do the test as it is now if the version is 1.5.x, and use the new result if the version is later than that.

Also have to deal with the datetime failures, since that warning has changed.

2022-12-22 12:20 UTC, ramvikrams commented
Sir I was testing but i am facing a wired error if I run `poe commands` without entering the virtual envirnment it works, but if I enter the virtual envirnment by `poetry shell` the `poe commands` show `ModuleNotFoundError` error.

2022-12-29 14:16 UTC, Dr-Irv commented
closing in favor of #485

2022-12-29 14:16 UTC, closed without merging