added list[Levels] to Dataframe.stack()
pandas-dev/pandas-stubs pull request #491
Opened 2022-12-31 11:55 UTC by muddi900

- [x] Closes #489 
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

2023-01-02 20:14 UTC, Dr-Irv requested changes
Can you please add a test corresponding to the code from the issue, and also an example that tests a single level?

2023-01-03 14:39 UTC, Dr-Irv requested changes

2023-01-03 16:45 UTC, muddi900 commented on tests/test_frame.py
> +            df_multi_level_cols2.stack([0, 1]), Union[pd.DataFrame, pd.Series[Any]]
When I don't use the generic it fails pyright tests on 3.10.

```bash
 /home/muddi900/src/pandas-stubs/tests/test_frame.py:1809:21 - error: "assert_type" mismatch: expected "DataFrame | Series[Unknown]" but received "DataFrame | Series[Any]" (reportGeneralTypeIssues)
  /home/muddi900/src/pandas-stubs/tests/test_frame.py:1813:21 - error: "assert_type" mismatch: expected "DataFrame | Series[Unknown]" but received "DataFrame | Series[Any]" (reportGeneralTypeIssues)
2 errors, 0 warnings, 0 informations 
```

2023-01-03 17:33 UTC, Dr-Irv requested changes
Based on this: https://github.com/pandas-dev/pandas-stubs/actions/runs/3831371047/jobs/6520515609

you need to run the pre-commit action to format the files.

If you do `poetry run poe style`, that should fix the issue.

2023-01-04 15:33 UTC, Dr-Irv commented
@muddi900 It turns out that we had an issue with our CI due to a SQLAlchemy update.  This was just fixed in #496. 

Can you merge with upstream/main and push, and ping here so I can trigger the tests?  Code looks good at this point, so just need it to pass our CI.

2023-01-05 14:36 UTC, Dr-Irv approved these changes
Thanks @muddi900

2023-01-05 14:36 UTC, merged