Fix #37 issue
pandas-dev/pandas-stubs pull request #52
Opened 2022-06-29 16:14 UTC by BrenoJesusFernandes

Basically, now `my_path.pth` is created and destroyed after tests.

2022-06-29 23:13 UTC, Dr-Irv requested changes
Need to only have changes related to fixing the `mypy_path.pth` file, and account for a possible failure.

2022-06-29 23:13 UTC, Dr-Irv commented on scripts/test/procedures.py
> +def add_last_changes():
This should be part of a different PR

2022-06-29 23:13 UTC, Dr-Irv commented on scripts/test/procedures.py
> +    create_mypy_pkg_file()
When testing the distribution, you do NOT want to have this file present, as the distribution is installed

2022-06-29 23:13 UTC, Dr-Irv commented on scripts/test/procedures.py
> +def restore_last_changes():
should be a different PR

2022-06-29 23:13 UTC, Dr-Irv commented on scripts/test/procedures.py
>      subprocess.run(cmd, check=True)
If for some reason this fails, the file would still be there.  Can't you use the `rollback` technique you have used elsewhere in case of failure?

2022-06-30 00:08 UTC, Dr-Irv commented on scripts/test/__init__.py
>          Step(name="Run Mypy Against Source Code", run=procedures.run_mypy_src),
don't you need a rollback here?

2022-06-30 00:35 UTC, twoertwein commented on scripts/test/procedures.py
> +    pkg_path = [path for path in sys.path if path.endswith('site-packages')]
A contextmanager would here also be nice, but I'm not sure whether that fits easily in the structure of having multiple steps.

2022-07-02 19:20 UTC, Dr-Irv commented
Can you merge with `main` and resolve conflicts?

2022-07-02 21:32 UTC, BrenoJesusFernandes commented
> Can you merge with `main` and resolve conflicts?

Done

2022-07-03 17:54 UTC, Dr-Irv approved these changes

2022-07-03 17:54 UTC, merged

2022-07-03 17:54 UTC, Dr-Irv commented
Thanks @BrenoJesusFernandes