Cover pandas.tseries.holiday
pandas-dev/pandas-stubs pull request #645
Opened 2023-04-13 08:41 UTC by adamchainz

I've tried to add typse for everything in this module. I'm not too confident about my overloads or Series/DatetimeIndex usage, please check that!

- [n/a] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

2023-04-13 11:45 UTC, Dr-Irv requested changes
Thanks for submitting this.  I would suggest setting up the environment for development (see https://github.com/pandas-dev/pandas-stubs/blob/main/docs/setup.md ) so you can test locally and not wait for the CI to identify issues.

Secondly, can you add a set of tests for these, using `check` and `assert_type()`.  Since we don't document these classes in the reference manual, just using the code shown in https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html?highlight=abstractholidaycalendar#holidays-holiday-calendars would be sufficient.  You could create a new file called `test_holidays.py` to accomplish this.

2023-04-13 11:45 UTC, Dr-Irv commented on pandas-stubs/tseries/holiday.pyi
> +        observance: None = ...,
I think `observance` should be `Callable[[datetime], datetime] | None`

2023-04-13 11:45 UTC, Dr-Irv commented on pandas-stubs/tseries/holiday.pyi
> +def get_calendar(name: str) -> "AbstractHolidayCalendar": ...
If you put `from __future__ import annotations` at the top of this file, then you can remove the quotes around `"AbstractHolidayCalendar"` in this line and the above, as well as in places below.

2023-04-13 11:45 UTC, Dr-Irv commented on pandas-stubs/tseries/holiday.pyi
> +    _cache: list[tuple[Timestamp, Timestamp, Series[datetime]]] | None = ...
remove the `_cache` - it's not public

2023-04-13 11:45 UTC, Dr-Irv commented on pandas-stubs/tseries/holiday.pyi
> +    ) -> None: ...
Same as above - swap the overloads.  First one should be `inplace: Literal[True]`, returning `None`.  Second one is `inplace: bool = ...` returning `list[Holiday]`

2023-04-13 12:16 UTC, adamchainz reviewed
Thank you for the swift review! Working on fixes and tests now.

2023-04-13 13:01 UTC, Dr-Irv commented
ping when green and when you added the tests.

2023-04-13 13:21 UTC, adamchainz commented
I started on tests but already hit an error where the doc'd example fails type checking, with a class I'm not touching here:

```
tests/test_holidays.py:25: error: Argument "weekday" to "DateOffset" has incompatible type "weekday"; expected "int"  [arg-type]
```

`DateOffset`'s docs don't say it allows taking a dateutil `weekday` object, but that's what was documented. I'm a bit out of my depth, I'm not sure how much I should expect the pandas docs to be correct/complete...

2023-04-13 14:18 UTC, Dr-Irv commented
> `DateOffset`'s docs don't say it allows taking a dateutil `weekday` object, but that's what was documented. I'm a bit out of my depth, I'm not sure how much I should expect the pandas docs to be correct/complete...

The problem is twofold.  One is that the pandas docs aren't documenting that we would accept a `dateutil._common.weekday` type as a value for the `weekday` parameter to `DateOffset`.  The second issue is that the type specification for the `weekday` argument in `pandas-stubs/_libs/tslibs/offsets.pyi` says it is an `int`.  You could fix the latter, but then we have to make `types-python-dateutil` a dependency, which involves modifying `pyproject.toml` and takes some care.

So for your PR, just leave out the `weekday` argument, and I think the tests will then work.

2023-04-13 14:21 UTC, Dr-Irv commented
Created an issue in pandas for the docs:  https://github.com/pandas-dev/pandas/issues/52650

2023-04-30 01:31 UTC, Dr-Irv approved these changes
thanks @adamchainz

2023-04-30 01:31 UTC, merged