GH - 624: Added `dtype` arg to `reaf_sql`
pandas-dev/pandas-stubs pull request #649
Opened 2023-04-17 05:32 UTC by ramvikrams

- [ ] Closes #xxxx (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

2023-04-19 13:19 UTC, twoertwein approved these changes

2023-04-20 19:11 UTC, Dr-Irv requested changes
Can you do 2 things here:

1. Another change to `read_sql()` is the introduction of the `dtype_backend` argument, so can you make that change in this PR?
2. Can you modify your test to use a different argument for `dtype`, e.g.,  something like`dtype={"int_column": float}` should work.  You may need to experiment with that.

2023-04-21 04:39 UTC, ramvikrams commented
> Can you do 2 things here:
> 
> 1. Another change to `read_sql()` is the introduction of the `dtype_backend` argument, so can you make that change in this PR?
> 2. Can you modify your test to use a different argument for `dtype`, e.g.,  something like`dtype={"int_column": float}` should work.  You may need to experiment with that.

Done

2023-04-21 12:22 UTC, Dr-Irv requested changes

2023-04-21 12:22 UTC, Dr-Irv commented on tests/test_io.py
> +def test_read_sql_dtypes2() -> None:
combine with above

2023-04-21 12:26 UTC, ramvikrams commented on pandas-stubs/io/sql.pyi
> +    dtype_backend: None = ...,
> You have these backwards.  Also, type of `dtype_backend` should be `dtype_backend: DtypeBackend | NoDefault = ...` where `DtypeBackend` goes into `_typing.pyi` as the last line reading `DtypeBackend = Literal["pyarrow", "numpy_nullable"]` and `NoDefault` is defined in `pandas._libs.lib`

Yes I was about to ask whether I can create `DtypeBackend`. I'll do the changes

2023-04-21 12:26 UTC, ramvikrams commented on pandas-stubs/io/sql.pyi
> +    dtype_backend: None = ...,
> > You have these backwards.  Also, type of `dtype_backend` should be `dtype_backend: DtypeBackend | NoDefault = ...` where `DtypeBackend` goes into `_typing.pyi` as the last line reading `DtypeBackend = Literal["pyarrow", "numpy_nullable"]` and `NoDefault` is defined in `pandas._libs.lib`
> 
> Yes I was about to ask whether I can create `DtypeBackend`. I'll do the changes now

2023-04-21 14:17 UTC, ramvikrams commented on pandas-stubs/io/sql.pyi
> +    dtype_backend: None = ...,
Done

2023-04-21 14:18 UTC, ramvikrams commented on tests/test_io.py
> +def test_read_sql_dtype1() -> None:
Done

2023-04-21 14:18 UTC, ramvikrams commented on tests/test_io.py
> +def test_read_sql_dtypes2() -> None:
Done

2023-04-21 14:48 UTC, Dr-Irv approved these changes
thanks @ramvikrams

2023-04-21 14:48 UTC, merged