Adds 'date_format' parameter to 'read_csv'
pandas-dev/pandas-stubs pull request #650
Opened 2023-04-17 15:09 UTC by SjorsLockhorst

Hey there, first PR in open source for me! 😄 
Glad to hear your thoughts / if I did it correctly.
Happy to correct anything.

- [x] Closes #636
- [x] Tests added: Please use `assert_type()` to assert the type of any return value

2023-04-19 13:20 UTC, twoertwein approved these changes

2023-04-20 19:39 UTC, Dr-Irv requested changes

2023-04-20 19:39 UTC, Dr-Irv commented on pandas-stubs/io/parsers/readers.pyi
> +    date_format: str | Mapping[str, str] | None = ...,
This should be `Mapping[int | str, str]` since an integer column number is accepted.

2023-04-20 19:39 UTC, Dr-Irv commented on tests/test_io.py
> +        )
I think the proper test here is to have a CSV file that has dates in it.  So if you create a new CSV file, using the pattern at the top of this function, with `"col1": ["2023-03-15", "2023-04-20"]`, and then use `parse_dates=["col1"]` in both of the tests you wrote, and a third test using `date_format={1: "%Y-%m-%d"}` that will test the variety of options.

2023-04-24 16:01 UTC, Dr-Irv approved these changes
Thanks @SjorsLockhorst

2023-04-24 16:01 UTC, merged