nightly fix for GH-657
pandas-dev/pandas-stubs pull request #660
Opened 2023-04-25 05:41 UTC by ramvikrams

- [x] Closes #657
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

2023-04-25 09:45 UTC, ramvikrams commented
The pytest nightly still fails even after copying the exact warnings

2023-04-25 15:35 UTC, ramvikrams commented on tests/test_api_types.py
> +        match="is_period_dtype is deprecated and will be removed in a future version. Use `isinstance(dtype, pd.PeriodDtype)` instead",
Done and nightly passes now

2023-04-25 19:43 UTC, Dr-Irv requested changes
can you change the lower bounds to 2.0.99 instead of 2.0.0 throughout your changes?

2023-04-26 07:45 UTC, ramvikrams commented
> can you change the lower bounds to 2.0.99 instead of 2.0.0 throughout your changes?

Done

2023-04-26 14:06 UTC, Dr-Irv approved these changes
thanks @ramvikrams

2023-04-26 14:06 UTC, merged