pd.RangeIndex should accept range as the first argument
pandas-dev/pandas-stubs pull request #686
Opened 2023-05-07 15:29 UTC by kshitiz305

- [x] Closes #677  (Replace xxxx with the Github issue number)
- [x] Tests added: Please use `assert_type()` to assert the type of any return value

2023-05-07 16:25 UTC, Dr-Irv requested changes
Can you add a test to `tests/test_indexes.py` that instantiates a `RangeIndex` with a `range` argument, using `check` and `assert_type` as in other tests?

2023-05-07 16:25 UTC, Dr-Irv commented on pandas-stubs/_version.pyi
> +_stub_version: Literal["2.0.1.230507"]
Please don't update `_stub_version`.  We're only doing that with releases.

2023-05-07 16:25 UTC, Dr-Irv commented on pyproject.toml
> +version = "2.0.1.230507"
Please don't update this

2023-05-08 10:56 UTC, kshitiz305 commented
> Can you add a test to `tests/test_indexes.py` that instantiates a `RangeIndex` with a `range` argument, using `check` and `assert_type` as in other tests?

let me push the code with the required test.

2023-05-21 21:42 UTC, Dr-Irv commented
@kshitiz305 checking on status of this PR

2023-05-24 10:36 UTC, kshitiz305 commented
@Dr-Irv Kindly have a look test for the range have been pushed

2023-05-24 16:02 UTC, Dr-Irv commented
Once #709 is merged, you will need to merge that in and revert changes to the 2 files I indicated.

2023-05-24 17:50 UTC, Dr-Irv commented
@kshitiz305 #709 has been merged, so can you merge with `main`, fix the reported issues, and push, then we can run the tests to see if everything works

2023-05-25 18:06 UTC, Dr-Irv requested changes

2023-05-26 16:26 UTC, kshitiz305 commented on pandas-stubs/core/indexes/range.pyi
>      def __init__(
Shall I delete the entire def __new__() or just the range as in the absence of the range in the __new__() it is returning an error.

2023-05-28 12:24 UTC, twoertwein commented on pandas-stubs/core/indexes/range.pyi
>      def __init__(
Shouldn't we remove the enitre `__init__` method? `__new__` exists in the pandas code https://github.com/pandas-dev/pandas/blob/8cf4ab491b06274f555d1ea305c172354208747a/pandas/core/indexes/range.py#L112 but `__init__` doesn't

2023-05-28 12:27 UTC, twoertwein commented on pyproject.toml
> +version = "2.0.1.230507"
I think you can simply run `git checkout <commit hash from before you made any changes> pandas-stubs/_version.pyi pyproject.toml` to revert these two files to what they were before.

2023-06-02 12:56 UTC, Dr-Irv requested changes
You also should do `poetry run poe style` before the next push, as the CI is failing because of that.

2023-06-02 12:56 UTC, Dr-Irv commented on pandas-stubs/core/indexes/range.pyi
>      def __new__(
Better to keep `__init__()` and remove `__new__()`
```suggestion
    def  __init__(
```

2023-07-03 20:23 UTC, kshitiz305 commented
@Dr-Irv  commit [6d89c40](https://github.com/pandas-dev/pandas-stubs/pull/686/commits/6d89c401fb745727678010d092546f7d598f3ade) 

Could you help me with this if this shall include the __new__ or __ init__ as this is leading a confusion and also failing **pyright**

2023-07-04 20:08 UTC, Dr-Irv requested changes

2023-07-04 20:08 UTC, Dr-Irv commented on pandas-stubs/core/indexes/range.pyi
> +        cls,
This should be `self`, because it is in `__init__()`

I think this is the cause of the pyright error you are getting.

2023-08-13 21:54 UTC, Dr-Irv commented
@kshitiz305 can you merge with main and get this finished up?

2023-09-06 09:33 UTC, closed without merging