Replace flake8 and pyupgrade with ruff
pandas-dev/pandas-stubs pull request #754
Opened 2023-07-20 14:22 UTC by twoertwein

Pandas switched to ruff a while ago: ruff is much faster and combines many different tools (including flake8-pyi and pyupgrade).

ruff fails currently because of this line which looks a bit weird:
https://github.com/pandas-dev/pandas-stubs/blob/89e083bf5548c6c944adbce74543437f7042c85c/pandas-stubs/io/formats/style.pyi#L43

2023-07-20 15:03 UTC, twoertwein commented on scripts/test/run.py
> +    cmd = ["mypy", "pandas-stubs", "tests"]
It doesn't seem to fail anymore :) Running `poe mypy` twice takes for me 44.882s and then 0.710s.

2023-07-20 15:30 UTC, Dr-Irv requested changes

2023-07-20 15:35 UTC, twoertwein commented on .pre-commit-config.yaml
> +          --per-file-ignores, "_*.pyi:PYI001, _*.pyi:PYI030",
I assume we want to keep them: https://github.com/pandas-dev/pandas-stubs/blob/89e083bf5548c6c944adbce74543437f7042c85c/pandas-stubs/_typing.pyi#L94

Will add line-based ignores instead.

2023-07-20 15:37 UTC, Dr-Irv commented on .pre-commit-config.yaml
> +          --per-file-ignores, "_*.pyi:PYI001, _*.pyi:PYI030",
> Will add line-based ignores instead.

I agree that we should keep those, so using line-based ignores at least makes us think about it whenever they come up

2023-07-20 15:39 UTC, twoertwein commented on pandas-stubs/core/indexes/accessors.pyi
> +    _PeriodProperties[  # noqa: F821
Changed the order. This is a ruff (and flake8) bug - the order shouldn't matter inside a pyi file.

2023-07-20 16:12 UTC, Dr-Irv approved these changes
Thanks @twoertwein

2023-07-25 16:33 UTC, Dr-Irv commented
@twoertwein  So I thanked you for this, then forgot to merge, and now there is a conflict. Can you resolve that conflict and push again?

2023-07-25 18:40 UTC, Dr-Irv approved these changes
thanks @twoertwein

2023-07-25 18:40 UTC, merged