Update timestamps.pyi
pandas-dev/pandas-stubs pull request #818
Opened 2023-11-10 01:16 UTC by davetapley

https://github.com/pandas-dev/pandas/commit/f3c46cd0899d5e11e0602798d9390c90e51e9ba7

https://github.com/pandas-dev/pandas/pull/48819

https://github.com/pandas-dev/pandas-stubs/issues/797

- [x] Closes #797 (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

2023-11-10 14:47 UTC, Dr-Irv requested changes
Can you add tests for this?

2023-11-10 19:49 UTC, davetapley reviewed
Hope this is sufficient 🙏🏻

2023-11-10 20:07 UTC, Dr-Irv requested changes

2023-11-10 20:07 UTC, Dr-Irv commented on pandas-stubs/_libs/tslibs/timestamps.pyi
> +    def as_unit(self, unit: str, round_ok: bool = ...) -> Timestamp: ...
The only possible values for the return of `unit` are `Literal["s", "ms", "us", "ns"]`  In pandas, this is now defined in `pandas._typing.py` via:
```python
TimeUnit = Literal["s", "ms", "us", "ns"]
```
So can you do the following:
1. Add that line to `pandas-stubs/_typing.pyi` 
2. Make the return value of `unit` be `TimeUnit`
3. Make the allowable values of `unit` in `as_unit` to be `TimeUnit`

You probably will have to change the test for `ts.unit` to use `assert_type()` testing against `TimeUnit`

If you want to go beyond that, the declaration `Literal["s", "ms", "us", "ns"]` appears in the following files and should be replaced with `TimeUnit`:

- pandas-stubs/core/frame.pyi
- pandas-stubs/core/indexes/datetimes.pyi
- pandas-stubs/core/series.pyi
- pandas-stubs/io/json/_json.pyi

But if you don't want to make that change, it's OK - I can just create a new issue for that once this PR is done.

2023-11-10 20:07 UTC, Dr-Irv commented on tests/test_scalars.py
> +    check(assert_type(ts2.as_unit('ns'), pd.Timestamp), pd.Timestamp)
```suggestion
    check(assert_type(ts2.as_unit("ns"), pd.Timestamp), pd.Timestamp)
```
use the pre-commit hook.  You need double quotes here.

2024-02-12 17:34 UTC, Dr-Irv commented
Closing in favor of #864

2024-02-12 17:34 UTC, closed without merging