Add `unit` property and `as_unit` method to `Timestamp`, `Timedelta` and `NaTType`
pandas-dev/pandas-stubs pull request #864
Opened 2024-02-12 05:03 UTC by skatsuta

- [x] Closes #797
- [x] Closes #859 
- [x] Tests added: Please use `assert_type()` to assert the type of any return value

Add `unit` property and `as_unit` method to `Timestamp`, `Timedelta` and `NaTType`.

Adding them to `DatetimeIndex`, `TimedeltaIndex` and `Series.dt` will be done in another PR.

2024-02-12 17:33 UTC, Dr-Irv requested changes
Suggest using `TimeUnit` that is now in pandas.

2024-02-12 17:33 UTC, Dr-Irv commented on pandas-stubs/_libs/tslibs/nattype.pyi
> +    ) -> Self: ...
Can you create a new type in `_typing.pyi` called `TimeUnit` that is `Literal["s", "ms", "us", "ns"]` and use that as the return type of `unit` and as the argument to `as_unit()` ?
Also replace wherever we have in the stubs that `Literal` and use `TimeUnit` instead.

Note that `TimeUnit` is now in `pandas/_typing.py` .

2024-02-12 17:33 UTC, Dr-Irv commented on tests/test_scalars.py
> +    check(assert_type(td.unit, str), str)
Since `TimeUnit` is in `pandas`, you could import that and use it here in the `assert_type` test.

2024-02-12 17:34 UTC, Dr-Irv commented
Closing in favor of #864

2024-02-13 13:41 UTC, skatsuta reviewed
@Dr-Irv Thanks for your suggestion.

Defined the `TimeUnit` type alias and used it throughout the stubs.

Also rebased to resolve conflicts with the main branch, so apologize if additional changes are not clear.

Will update #865 to use `TimeUnit` as well once this PR gets merged.

2024-02-13 14:40 UTC, Dr-Irv approved these changes
thanks @skatsuta

2024-02-13 14:40 UTC, merged