Added types to df.info()
pandas-dev/pandas-stubs pull request #875
Opened 2024-02-21 22:38 UTC by askmyhat

2024-02-22 02:11 UTC, twoertwein reviewed
Can you please add a test case, something like:
```py
check(assert_type(df.info(show_counts=True), None), None)
check(assert_type(df.info(show_counts=None), None), None)
```

2024-02-22 02:11 UTC, twoertwein commented on pandas-stubs/core/frame.pyi
> +        self, verbose=..., buf=..., max_cols=..., memory_usage=..., show_counts=...
I believe you can also add the types `show_counts: bool | None = ...`

2024-02-22 19:51 UTC, Dr-Irv requested changes
Some small changes

2024-02-22 19:51 UTC, Dr-Irv commented on pandas-stubs/core/frame.pyi
> +        memory_usage: bool | str | None = ...,
The `str` value can only be `Literal["deep"]` according to the docs.

2024-02-22 19:51 UTC, Dr-Irv commented on tests/test_frame.py
> +    check(assert_type(df.info(verbose=None), None), type(None))
For any of these tests that are testing values of  `True` and `None`, should also add a test testing a value of `False`

2024-02-23 18:30 UTC, Dr-Irv approved these changes
thanks @askmyhat

2024-02-23 18:30 UTC, merged