Fixed TYP of values argument of the pandas.DataFrame.pivot_table
pandas-dev/pandas-stubs pull request #893
Opened 2024-03-20 00:09 UTC by Aftabby

This pull request addresses _issue #885_ by modifying the _pivot_table_ stub definition in _frame.pyi_ to allow lists of strings as the values argument. Previously, the stub definition only supported single strings or None for values.

**Changes Introduced:**
Updated the values argument type in the _pivot_table_ stub definition to include _Sequence[_str]_. This allows lists of strings to be used for values.

**Test Case:**
No test case added as there was already an existing test case in the file test_frame.py on line 922 : 
check(
```
assert_type(
df.pivot(index="col1", columns="col3", values=["col2", "col4"]),
pd.DataFrame,
),
pd.DataFrame,
)
```
Which already test the addressed issue and updated fix.

[ ] Closes #885

2024-03-20 19:18 UTC, Aftabby commented
Hello @Dr-Irv , I have included the test case. Can you please have a look and check if it is alright.

2024-03-20 19:47 UTC, Dr-Irv requested changes

2024-03-20 19:47 UTC, Dr-Irv commented on tests/test_frame.py
> +            df.pivot_table(index="col2", columns="col4", values=["col1", "col3"]), pd.DataFrame,
Your test is invalid for pandas.  Use this:
```suggestion
            df.pivot_table(index="col1", columns="col3", values=["col2", "col4"]), pd.DataFrame,
```

2024-03-20 22:16 UTC, Aftabby commented
Changed per your suggestion. Thanks!

2024-03-20 22:23 UTC, Dr-Irv requested changes
Now you are failing because you didn't install the pre-commit hooks.  Please follow the instructions here:  https://github.com/pandas-dev/pandas-stubs/blob/main/docs/setup.md to set up your environment. 

If you then just add one space character to `tests/test_frame.py`, and commit, then `black` will reformat the code and fix the issue.

Or you can try editing by hand if you look at what `black` did at https://github.com/pandas-dev/pandas-stubs/actions/runs/8366596481/job/22907251773?pr=893

But that's rather risky - you're better off setting up the environment and let the tools do the work for you.

2024-03-20 23:19 UTC, Aftabby commented
Hopefully, no more formatting issue now.

2024-03-21 12:31 UTC, Dr-Irv approved these changes
thanks @Aftabby

2024-03-21 12:31 UTC, merged