Add calamine Excel reader
pandas-dev/pandas-stubs pull request #898
Opened 2024-03-31 01:52 UTC by davetapley

Since https://github.com/pandas-dev/pandas/pull/54998

No existing tests covering `engine`, I can add if needed?

2024-03-31 02:27 UTC, Dr-Irv commented
Thanks for the PR.  Would like opinion of @twoertwein to determine if we should add tests for `engine` keyword.  On the one hand, it would be nice to have for completeness.  On the other hand, we'd have to add a build dependency for `calamine`, which might be fine to do assuming all the installation issues work out for developers and in CI.

2024-03-31 02:29 UTC, Dr-Irv requested changes

2024-03-31 02:29 UTC, Dr-Irv commented on pandas-stubs/io/excel/_base.pyi
> +    TypeAlias,
You'll need to import `TypeAlias` from `typing_extensions` so we can support earlier versions of python.

2024-03-31 02:32 UTC, Dr-Irv commented
Also, CI is failing because a change was made in pyright 1.1.356, so you can lock down pyright to 1.1.354 in this PR in `pyproject.toml`.  There's another PR out there that will allow us to upgrade pyright to 1.1.356

2024-03-31 02:39 UTC, twoertwein commented
>  we'd have to add a build dependency for `calamine`, which might be fine to do assuming all the installation issues work out for developers and in CI.

I'm not familiar with how python-calamine is packaged. Assuming its pypi package contains everything to test it, I don't see a reason not to make it a development dependency. If we have to install packages that are not on Pypi, I would be inclined to have tests inside a TYPE_CHECKING block instead.

2024-04-01 14:29 UTC, Dr-Irv commented
> > we'd have to add a build dependency for `calamine`, which might be fine to do assuming all the installation issues work out for developers and in CI.
> 
> I'm not familiar with how python-calamine is packaged. Assuming its pypi package contains everything to test it, I don't see a reason not to make it a development dependency. If we have to install packages that are not on Pypi, I would be inclined to have tests inside a TYPE_CHECKING block instead.

It is on pypi and conda-forge, so I think we'd be OK.  I was concerned that it is built on top of rust, and I don't know if that means a whole lot of other stuff gets installed as a result.

@davetapley Open to have you add tests to this PR

2024-04-03 22:21 UTC, Dr-Irv requested changes
Can you merge with `upstream/main` - CI is failing because of that.  And update the pyright version as indicated.

2024-04-03 22:21 UTC, Dr-Irv commented on pyproject.toml
> +pyright = "=1.1.354"
#897 fixed this issue, so you can use `pyright = ">=1.1.357"` and CI should pass

2024-04-04 20:07 UTC, twoertwein commented on pandas-stubs/io/excel/_base.pyi
> +ReadEngine: TypeAlias = Literal["xlrd", "openpyxl", "odf", "pyxlsb", "calamine"]
Could go in `pandas._typing`.

2024-04-05 23:38 UTC, twoertwein approved these changes

2024-04-09 15:28 UTC, merged