Fix nightly
pandas-dev/pandas-stubs pull request #904
Opened 2024-04-07 14:46 UTC by twoertwein

There are still four issues on nightly - might be a pandas bug?

> FAILED tests/test_groupby.py::test_frame_groupby_ewm - AttributeError: 'ExponentialMovingWindowGroupby' object has no attribute 'apply'. Did you mean: '_apply'?
> FAILED tests/test_groupby.py::test_series_groupby_ewm - AttributeError: 'ExponentialMovingWindowGroupby' object has no attribute 'apply'. Did you mean: '_apply'?
> FAILED tests/test_windowing.py::test_ewm_aggregate - AttributeError: 'ExponentialMovingWindow' object has no attribute 'apply'. Did you mean: '_apply'?
> FAILED tests/test_windowing.py::test_ewm_aggregate_series - AttributeError: 'ExponentialMovingWindow' object has no attribute 'apply'. Did you mean: '_apply'?

2024-04-07 14:48 UTC, twoertwein commented on pandas-stubs/core/indexes/timedeltas.pyi
> -        unit: Literal["D", "h", "m", "s", "ms", "us", "ns"] = ...,
warns in the current release and errors in the next release

2024-04-09 22:41 UTC, twoertwein commented on tests/test_pandas.py
> +            check(assert_type(uniques, np.ndarray), np.ndarray)
Sounds like a good idea as this is a breaking change in 3.0

2024-04-09 22:47 UTC, twoertwein commented on tests/test_scalars.py
>          check(assert_type(pd.Timedelta(1, "H"), pd.Timedelta), pd.Timedelta)
The stubs use `str` not a `Literal`

2024-04-10 15:38 UTC, Dr-Irv commented on tests/test_scalars.py
>          check(assert_type(pd.Timedelta(1, "H"), pd.Timedelta), pd.Timedelta)
No, I see in `pandas-stubs\_libs\tslibs\timedeltas.pyi` that we have `TimeDeltaUnitChoices` that restricts the parameter.

2024-04-11 00:41 UTC, twoertwein commented on tests/test_scalars.py
>          check(assert_type(pd.Timedelta(1, "H"), pd.Timedelta), pd.Timedelta)
Thanks! Sorry, the parameters that I spot-checked were using str

2024-04-11 14:10 UTC, Dr-Irv commented
@twoertwein let me know when I should review again, although I probably won't be able to look at it until April 17.

2024-04-11 22:45 UTC, twoertwein commented
> @twoertwein let me know when I should review again, although I probably won't be able to look at it until April 17.

Should be ready now

2024-04-14 15:34 UTC, Dr-Irv requested changes
A few more things to fix

2024-04-14 15:34 UTC, Dr-Irv commented on tests/test_scalars.py
> +    check(assert_type(pd.Timedelta(1, "ns"), pd.Timedelta), pd.Timedelta)
I think all of these tests are in the code below, so this can be deleted.

2024-04-14 15:34 UTC, Dr-Irv commented on pandas-stubs/_libs/tslibs/timedeltas.pyi
> -    "N",
Need to remove `"t"`, `"u"`, `"l"` and `"n"` as well

2024-04-17 16:14 UTC, Dr-Irv approved these changes
thanks @twoertwein

2024-04-17 16:14 UTC, merged

2024-04-17 16:45 UTC, Dr-Irv commented
> There are still four issues on nightly - might be a pandas bug?
> 
> > FAILED tests/test_groupby.py::test_frame_groupby_ewm - AttributeError: 'ExponentialMovingWindowGroupby' object has no attribute 'apply'. Did you mean: '_apply'?
> > FAILED tests/test_groupby.py::test_series_groupby_ewm - AttributeError: 'ExponentialMovingWindowGroupby' object has no attribute 'apply'. Did you mean: '_apply'?
> > FAILED tests/test_windowing.py::test_ewm_aggregate - AttributeError: 'ExponentialMovingWindow' object has no attribute 'apply'. Did you mean: '_apply'?
> > FAILED tests/test_windowing.py::test_ewm_aggregate_series - AttributeError: 'ExponentialMovingWindow' object has no attribute 'apply'. Did you mean: '_apply'?

@twoertwein 
We are still failing due to the above. Can you post an issue in `pandas` about those?

There is also a test failing due to bitwise operator behavior changing.

2024-04-17 21:36 UTC, twoertwein commented
I can look into the new failures when it is clear whether the ExponentialMovingWindow errors are intended or not.

Opened https://github.com/pandas-dev/pandas/issues/58299