ENH: updating subset types in drop_duplicates/duplicated
pandas-dev/pandas-stubs pull request #986
Opened 2024-08-26 11:16 UTC by kirill-bash

- [ ] Closes #59237 (Replace xxxx with the Github issue number)
- [ ] Tests added: Please use `assert_type()` to assert the type of any return value

2024-08-26 11:17 UTC, kirill-bash commented
Follow-up to https://github.com/pandas-dev/pandas/pull/59392

2024-08-26 22:49 UTC, Dr-Irv requested changes
Can you add a test for this in `tests/test_frame.py` ?

2024-08-28 22:16 UTC, kirill-bash commented
@Dr-Irv,

I have added a test for the supported arguments.

2024-08-28 22:20 UTC, Dr-Irv requested changes

2024-08-28 22:20 UTC, Dr-Irv commented on tests/test_frame.py
> +def test_types_drop_duplicates(drop_arg) -> None:
For the purposes of testing type checks, you have to explicitly put in each of these arguments and can't parameterize.   So you'd do:
```python
check(assert_type(df.drop_duplicates({"AAA"}), pd.DataFrame), pd.DataFrame)
check(assert_type(df.drop_duplicates(["AAA"]), pd.DataFrame), pd.DataFrame)
# and similar for the other 3
```
Then you don't need to do `assert_frame_equal()`

2024-08-28 22:59 UTC, kirill-bash commented
@Dr-Irv,

Updated based on your feedback.

Thanks!

2024-08-29 23:59 UTC, kirill-bash commented on tests/test_frame.py
> +    check(assert_type(df.drop_duplicates("AAA"), pd.DataFrame), pd.DataFrame)
Thanks for the tip!

2024-09-03 16:29 UTC, Dr-Irv requested changes

2024-09-03 16:29 UTC, Dr-Irv commented on tests/test_frame.py
> +    if PD_LTE_22:
```suggestion
    if not PD_LTE_22:
```
You want this test to only be executed if we are in a version after pandas 2.2

2024-09-04 15:22 UTC, Dr-Irv requested changes
You need to run black on your changed files, or follow the instructions at https://github.com/pandas-dev/pandas-stubs/blob/main/docs/setup.md to set up your environment and install the pre-commit checks.

2024-09-06 20:48 UTC, Dr-Irv approved these changes
thanks @kirill-bash

2024-09-06 20:48 UTC, merged