Fix error when `sheet_name` is `None` for `read_excel`.
pandas-dev/pandas-stubs pull request #99
Opened 2022-07-05 20:13 UTC by aholmes

`pandas.read_excel` supports specifying `None` for `sheet_name`.
When using `None`, all worksheets are returned.

https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html#pandas.read_excel

- [ ] Closes #98
- [ ] Tests added: Added checks for overloads when `sheet_name` is `None`, an int, a list[int], or a list[int|str]

2022-07-05 21:07 UTC, Dr-Irv requested changes

2022-07-05 21:07 UTC, Dr-Irv commented on tests/test_frame.py
> +        df14: Dict[Union[int, str], pd.DataFrame] = pd.read_excel(
Can you leave `df13` as it was?  (now your `df14`) and make `df14` what you are now calling `df13` so we see the additional tests?

Then above the (new) `df14` add a reference to the Github issue, e.g., # GH 98

2022-07-06 01:56 UTC, aholmes commented on pandas-stubs/io/excel/_base.pyi
> +    sheet_name: Union[List[Union[int, str]], None],
> Can you make this `Optional[List[Union[int, str]]]` ?

Sure thing. A thought, although it doesn't make any practical difference - `sheet_name` is optional, but the default value is `0`. `None` is a specific value that must be specified if it is to be used and, as such, specifying `Optional` here to represent that `None` is a valid value is a misnomer.

2022-07-06 02:33 UTC, Dr-Irv commented on pandas-stubs/io/excel/_base.pyi
> +    sheet_name: Union[List[Union[int, str]], None],
> Sure thing. A thought, although it doesn't make any practical difference - `sheet_name` is optional, but the default value is `0`. `None` is a specific value that must be specified if it is to be used and, as such, specifying `Optional` here to represent that `None` is a valid value is a misnomer.

AFAIK, specifying `Optional` means that `None` is a valid value. That's different than saying `sheet_name: List[int, str] = ...`, which means the parameter is optional.  See https://docs.python.org/3/library/typing.html#typing.Optional

2022-07-06 02:40 UTC, Dr-Irv commented
Thanks @aholmes

2022-07-06 02:40 UTC, merged